configValidationMode: off
frameworkVersion: ^2.39.1

service: scheduled-maintenance

config:
  accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
  zoneId: ${env:CLOUDFLARE_ZONE_ID}

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  scheduled-maintenance:
    name: scheduled-maintenance
    script: ${env:ARTIFACT_PATH}
    events:
      - http:
          url: hydragents.xyz/*
