configValidationMode: off
frameworkVersion: '3'

service: scheduled-maintenance

provider:
  name: cloudflare
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  scheduled-maintenance:
    name: scheduled-maintenance
    script: ${env:ARTIFACT_PATH}
    events:
      - http:
          url: api.dwolla.com/*
      - http:
          url: dashboard.dwolla.com/*
      - http:
          url: accounts.dwolla.com/*
      - http:
          url: partners.dwolla.com/*
      - http:
          url: transfer.dwolla.com/*
